### ISSUE TITLE
need error log fall back.

### ISSUE THREAD

**Issue by sanguis** [Knectar/behat-ci#4]
the error log location should probably also be in the settings.yml file
- If it fails to be written it should fall back to
  ~/.logs/behat-ci.log
- Log writing failure should be a warning not fatal use a try catch loop (https://secure.php.net/manual/en/language.exceptions.php)

**Comment by jgeryk** [comment]
It is currently changeable in app/config/config.yml. I will add a fallback to ~/.logs/behat-ci.log, and maybe an option to turn off logging in settings.yml (trying to think if this is worth doing). This should eliminate the need to have the logger wrapped in a try/catch block wherever it's called, right?

**Comment by sanguis** [comment]
great!
